{% set name = "sympy_plot_backends" %}
{% set version = "3.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sympy_plot_backends-{{ version }}.tar.gz
  sha256: 84b79dd690d65e06ab8de4f0ca104ce8e2fde0f68cc4abaddf801704c0340021

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - packaging
    - appdirs >=1.4.4
    - numpy >=1.21.1
    - sympy >=1.10.1
    - matplotlib-base >3.4.2
    - mergedeep >=1.3.4

test:
  imports:
    - spb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Davide-sd/sympy-plot-backends
  summary: Backends for plotting with SymPy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Davide-sd
