{% set name = "sympy_plot_backends" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sympy_plot_backends-{{ version }}.tar.gz
  sha256: d9d71033fe36601bf800216a6b6c0ec8a9f4fe687acacc15b1a69bee1b1aef3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - packaging
    - appdirs >=1.4.4
    - numpy >=1.21.1
    - sympy >=1.10.1
    - matplotlib-base >3.4.2
    - mergedeep >=1.3.4

test:
  imports:
    - spb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Davide-sd/sympy-plot-backends
  summary: Backends for plotting with SymPy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Davide-sd
